server:
  port: 8081

spring:
  # PostgreSQL
  datasource:
    url: ${POS_DATABASE_URL}
    username: ${POS_DATABASE_USERNAME}
    password: ${POS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # MongoDB
  data:
    mongodb:
      uri: ${MONG_DATABASE_URI}

  #RabbitMQ
  rabbitmq:
    host: ${RAB_HOST}
    port: ${RAB_PORT}
    username: ${RAB_USERNAME}
    password: ${RAB_PASSWORD}
#    virtual-host: ${RAB_VHOST}