server:
  port: 5000

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/chatdb

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.format_sql: true